### ISSUE TITLE
Redesign IFDB's web site for modern web standards

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb-suggestion-tracker#106]
There are many suggestions which amount to "IFDB should use modern web standards". But there is an easier way than implementing 1000 suggestions. Scrap the existing web pages and make new better ones!

IFDB's website was designed over 10 years ago for small low-resolution desktop screens. It was fine at the time but today standards are higher and expectations have increased.

It will be easier to accommodate suggestions for changes in a new web site where there is more flexibility.

**Comment by qdacsvx** [comment]
Pick a web site you like (one with modern web design!) and imagine if IFDB was like that. Describe it.

I pick [tumblr](https://cutecatpics.tumblr.com/).

Most pages of IFDB could have a top bar with button links for navigation and a search box. Content would be an infinite scroll. Homepage. Searches. Flat reviews. Flat comments. Lists. Polls. There would be a few custom pages e.g. game pages but the idea would be a simple consistent layout.

If you want, make some prototype pages and share your ideas.

**Comment by dfabulich** [comment]
We're gradually working on individual pieces of this, but I think each one of these ideas needs/deserves its own separate issue.
