### ISSUE TITLE
Add description / image metadata to game details pages

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#12]
When you copy and paste a game link into the intfiction.org forum, it tries to generate a preview card for it, but IFDB is missing the metadata Discourse wants in order to make that card, so card generation fails. This sort of data is used on other sites as well, including Twitter, Facebook, etc.

We should put that metadata in so the cards will work, e.g. adding OpenGraph elements to the head.

**Comment by salty-horse** [comment]
Here's an example with the relevant elements:
```
<head>
<meta property="og:image" content="https://ifdb.tads.org/viewgame?coverart&id=ay0yfjdivax1m40e&thumbnail=175x175" />
<meta property="og:title" content="Byzantine Perspective" />
<meta property="og:site_name" content="IFDB" />
<meta property="og:url" content="https://ifdb.tads.org/viewgame?id=ay0yfjdivax1m40e" />
<meta property="og:type" content="website" />
<meta property=" Your task is simple enough. Just nab the chalice." />
</head>
```

For `og:image`, recommendations vary about dimensions, but I think the thumbnail is good enough.

**Comment by lkcampbell** [comment]
> `<meta property="Your task is simple enough. Just nab the chalice." />`

Is this tag missing an attribute?

I'm not sure how to test that the metadata is doing what it is supposed to do directly. Maybe we just make sure the tags are there, then deploy the change to production, then test with a link posting in intfiction.org afterwards?

**Comment by salty-horse** [comment]
@lkcampbell yes, sorry. This is supposed to be `property="og:description"`. I edited my post above.

To test, you can try local tools like this one:
https://chrome.google.com/webstore/detail/localhost-open-graph-chec/gcbnmkhkglonipggglncobhklaegphgn?hl=en

**Comment by lkcampbell** [comment]
@salty-horse Yup, that looks like the exact tool I need, thanks.

I will take this issue.

**Comment by lkcampbell** [comment]
Okay, the Chrome extension wouldn't work for me but I was able to set up a temporary local tunnel and test it using the Twitter Card Validator and it looks great! Going to check a few test cases and then will do the pull request a little later today. Thanks for the suggestion, really nice feature!
