### ISSUE TITLE
Sort by "Highest Ratings" shouldn't just sort by average rating

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#16]
If you Browse by "Highest Rated First," the first page will be full of games with perfect 5-star averages. These are typically games with a very small number of ratings, often just one rating. https://ifdb.tads.org/search?sortby=ratu&browse=1

To see the number of ratings, you can search for `#ratings:1-` and sort by "Highest Rated First," which typically shows a subtly different random set of games, but it makes it all the more obvious that these are games with just one or two 5-star ratings.
https://ifdb.tads.org/search?sortby=ratu&searchfor=%23ratings%3A1-

Sorting by average is a notorious bad practice; there are a number of alternative approaches. This article by Evan Miller discusses the problem https://www.evanmiller.org/how-not-to-sort-by-average-rating.html and includes a proposal for binary thumbs-up/thumbs-down "positive" and "negative" votes. He also has an article (more relevant to our situation) about sorting by star rating. https://www.evanmiller.org/ranking-items-with-star-ratings.html

I've posted a version of Evan Miller's algorithm in SQL. https://gist.github.com/dfabulich/fc6b13a8bffc5518c4731347de642749

IFDB should use that algorithm when sorting by rating.

**Comment by dfabulich** [comment]
Note that the IFDB Top 100 uses another approach. https://ifdb.tads.org/viewlist?id=k7rrytlz3wihmx2o 

> An automatically updated list utilizing an IMDb style Bayes estimator to calculate weighted ratings based on all IFDB ratings. > Questions and comments can be placed here.
>
>Formula used for weighted ratings:
>(r × v + c × m) ÷ (v + m)
>
>Where:
>r = average of ratings for the work
>v = number of ratings for the work
>c = the mean rating on all of IFDB (3.37)
>m = minimum amount of ratings required (12)

The "IFDB Top 100" approach requires a minimum number of ratings (12, in this example) which probably wouldn't work for arbitrary search filters. (By Evan Miller's algorithm doesn't require a minimum number of reviews.)

I claim that if IFDB were to adopt Evan Miller's algorithm, the IFDB Top 100 list might no longer be necessary.

**Comment by dfabulich** [comment]
It's especially galling that the "IFDB recommends" section on the footer of the home page doesn't prioritize games based on the number of reviews. It will cheerfully recommend 5-star games with just one review, which are hardly the best of the best.

**Comment by curiousdannii** [comment]
A Q&A on ranking ratings (but I don't understand all the maths): https://stats.stackexchange.com/questions/15979/how-to-find-confidence-intervals-for-ratings

**Comment by dfabulich** [comment]
Another thought here: emphasizing the number of reviews can exacerbate the effect of brigading.

It's not unheard of for authors to direct their fans to IFDB to upvote their game. That's not inherently bad, but IFDB is a small place, where even a dozen 5-star reviews would put a game in the top 1% of all games on the site, and a couple dozen of those puts you in the top tier of the IFDB Top 100.

Those fans aren't claiming that the game they're rating is "better" than other IF on the site; they're just expressing enthusiastic approval of the game they played. (Or, if they _are_ claiming that, their claim is unjustified, because they haven't even tried the other stuff.)

**Comment by dfabulich** [comment]
I wrote a SQL query for the top games according to Evan Miller's starsort algorithm. (I _think_ I got it right.)

```sql
select title, starsorted.* from games join (
    select
        pivoted.*,
        (
            rated1 + rated2*2 + rated3*3 + rated4*4 + rated5*5
        )/count as average,
        (
            (5*(rated5+1)+4*(rated4+1)+3*(rated3+1)+2*(rated2+1)+1*(rated1+1)
        )/(
            5+rated5+rated4+rated3+rated2+rated1
        ))-1.65*SQRT(
            (
                (
                    (25*(rated5+1)+16*(rated4+1)+9*(rated3+1)+4*(rated2+1)+1*(rated1+1))
                        /(rated5+rated4+rated3+rated2+rated1)
                ) - POWER(
                    (
                        (5*(rated5+1)+4*(rated4+1)+3*(rated3+1)+2*(rated2+1)+1*(rated1+1))
                            /(5+rated5+rated4+rated3+rated2+rated1)
                    ), 2
                )
            )/(6+rated5+rated4+rated3+rated2+rated1)) as weighted
        from (
            select
                gameid,
                sum(case when rating = 1 then count else 0 end) as rated1,
                sum(case when rating = 2 then count else 0 end) as rated2,
                sum(case when rating = 3 then count else 0 end) as rated3,
                sum(case when rating = 4 then count else 0 end) as rated4,
                sum(case when rating = 5 then count else 0 end) as rated5,
                sum(count) as count,
                max(moddate) as moddate
            from (
                select
                    count(id) as count,
                    max(moddate) as moddate,
                    rating,
                    gameid 
                from (
                    select
                        id,
                        rating,
                        gameid,
                        moddate
                    from reviews
                    INNER JOIN (
                        select
                            max(moddate) as moddate,
                            gameid,
                            userid 
                        from reviews
                        where
                            userid is not null
                            and rating is not null
                        group by gameid, userid
                    ) latest
                    USING (moddate, gameid, userid)
                ) deduped
                group by rating, gameid
            ) as grouped
            group by gameid
        ) as pivoted
    ) as starsorted
on games.id = gameid
order by weighted desc limit 100;
```

I ran this on the publicly accessible IFArchive data; here's what it came up with. These results look pretty good to me. (It does _not_ seem to increase the effect of brigading; if anything, it seems to have done the opposite.)

| title                                | gameid           | rated1 | rated2 | rated3 | rated4 | rated5 | count | moddate             | average | weighted           |
|--------------------------------------|:----------------:|:------:|:------:|:------:|:------:|:------:|:-----:|:-------------------:|:-------:|:------------------:|
| Counterfeit Monkey                   | aearuuxv83plclpl |      0 |      0 |      5 |     14 |    127 |   164 | 2021-01-07 09:07:31 |  4.3049 | 4.6302759741176525 |
| Anchorhead                           | op0uw1gn1tjqmjt7 |      1 |      8 |      9 |     61 |    242 |   321 | 2020-12-28 22:01:58 |  4.6667 |  4.555777526319797 |
| Lost Pig                             | mohwfk47yjzii14w |      2 |      0 |     27 |    152 |    234 |   420 | 2020-12-22 21:46:46 |  4.4310 |  4.398034146557527 |
| Superluminal Vagrant Twin            | 5xzoz5wimz4xxha  |      0 |      0 |      0 |     26 |     55 |    81 | 2020-07-20 00:44:24 |  4.6790 | 4.3439990432251765 |
| Violet                               | 4glrrfh7wrp9zz7b |      1 |      5 |     32 |    106 |    180 |   324 | 2020-12-09 19:29:21 |  4.4167 |  4.307558745183305 |
| 80 DAYS                              | du51t0qrhjqlnbij |      0 |      1 |      2 |      9 |     46 |    58 | 2020-12-27 13:40:20 |  4.7241 |  4.255079301940086 |
| Spider and Web                       | 2xyccw3pe0uovfad |      2 |     12 |     23 |     65 |    154 |   256 | 2020-12-17 03:08:03 |  4.3945 |  4.254189326589476 |
| Hadean Lands                         | u58d0mlbfwcorfi  |      0 |      1 |      1 |      5 |     41 |    52 | 2020-10-14 19:41:50 |  4.4231 |  4.229305910670526 |
| Photopia                             | ju778uv5xaswnlpl |      3 |     20 |     58 |    164 |    251 |   506 | 2020-12-12 15:16:00 |  4.2055 |  4.204704479820325 |
| Planetfall                           | xe6kb3cuqwie2q38 |      0 |      3 |      9 |     27 |     64 |   105 | 2021-01-15 22:21:45 |  4.3905 |  4.198948038228651 |
| Savoir-Faire                         | p0cizeb3kiwzlm2p |      3 |      2 |      7 |     30 |     73 |   115 | 2020-10-11 20:31:02 |  4.4609 | 4.1984624320442965 |
| The Wizard Sniffer                   | uq18rw9gt8j58da  |      0 |      1 |      5 |     24 |     49 |    79 | 2021-01-17 01:59:58 |  4.5316 |  4.189556458907745 |
| Bronze                               | 9p8kh3im2j9h2881 |      1 |      2 |     27 |    107 |    111 |   248 | 2021-01-03 01:22:03 |  4.3105 |   4.18246321592177 |
| Worlds Apart                         | 1aliwzro4e48mdlt |      1 |      1 |      9 |     13 |     57 |    81 | 2020-11-02 05:43:43 |  4.5309 |  4.181205951611339 |
| Trinity                              | j18kjz80hxjtyayw |      0 |      2 |      8 |     19 |     54 |    86 | 2020-12-12 15:36:45 |  4.3488 |  4.172257306270597 |
| Blue Lacuna                          | ez2mcyx4zi98qlkh |      3 |      2 |      6 |     21 |     65 |   102 | 2020-10-14 19:40:31 |  4.2549 |  4.167691386293938 |
| Slouching Towards Bedlam             | 032krqe6bjn5au78 |      0 |      5 |     24 |     67 |     90 |   190 | 2020-12-26 19:30:23 |  4.2105 |  4.135634394116956 |
| Eat Me                               | yutkd9u0oeog4br1 |      0 |      1 |      2 |     21 |     38 |    66 | 2020-12-14 05:07:09 |  4.2727 |  4.127157385614345 |
| Suveh Nux                            | xkai23ry99qdxce3 |      0 |      4 |     20 |     91 |     80 |   195 | 2020-10-17 23:38:04 |  4.2667 |   4.11433078366967 |
| Toby's Nose                          | xf5y04yekcrqtnc  |      0 |      1 |      5 |     18 |     40 |    64 | 2020-11-14 18:26:22 |  4.5156 | 4.1041872167153866 |
| City of Secrets                      | u6wzkckne4zsafyl |      0 |      2 |      7 |     38 |     46 |    93 | 2020-09-21 21:01:40 |  4.3763 |  4.088929482142819 |
| Coloratura                           | g0fl99ovcrq2sqzk |      1 |      0 |      8 |     28 |     45 |    82 | 2020-09-23 17:56:29 |  4.4146 |  4.086702066133981 |
| Birdland                             | ap1651hvjldbuugj |      2 |      4 |     11 |     42 |     62 |   121 | 2021-01-03 01:28:46 |  4.3058 |  4.063693471560095 |
| Enchanter                            | vu4xhul3abknifcr |      0 |      1 |      8 |     37 |     39 |    85 | 2020-12-17 07:30:47 |  4.3412 |  4.036417369874839 |
| Open Sorcery                         | hslgyznv9n2hou7k |      2 |      1 |      2 |      8 |     39 |    52 | 2020-12-09 23:30:07 |  4.5577 |  4.034392893588358 |
| Make It Good                         | jdrbw1htq4ah8q57 |      1 |      0 |      9 |     21 |     41 |    75 | 2020-09-01 17:58:40 |  4.2267 |   4.03364423152658 |
| The Gostak                           | w5s3sv43s3p98v45 |      0 |      4 |      3 |     22 |     39 |    70 | 2020-12-30 07:26:06 |  4.2857 |   4.02190447717262 |
| The Hitchhiker's Guide to the Galaxy | ouv80gvsl32xlion |      1 |      4 |     24 |     69 |     68 |   170 | 2021-01-11 00:49:12 |  4.1000 |  4.020862188324174 |
| Babel                                | z5xgyw0jbt9r3ah1 |      1 |      3 |     19 |     54 |     59 |   137 | 2021-01-09 19:26:21 |  4.1971 |  4.017852997346641 |
| A Mind Forever Voyaging              | 4h62dvooeg9ajtfa |      2 |      3 |     10 |     31 |     51 |   100 | 2020-12-17 07:32:38 |  4.1700 |  4.007730034815893 |
| Metamorphoses                        | j61yaux1cqbptxyb |      3 |      3 |     14 |     44 |     53 |   120 | 2021-01-09 11:03:20 |  4.1000 | 3.9590984792301445 |
| Vespers                              | 6dj2vguyiagrhvc2 |      0 |      8 |     19 |     73 |     57 |   157 | 2020-12-18 18:59:43 |  4.1401 | 3.9570910757389623 |
| Varicella                            | ywwlr3tpxnktjasd |      0 |      8 |     19 |     31 |     58 |   121 | 2021-01-01 22:58:34 |  4.0248 |   3.94902172870878 |
| Curses!                              | plvzam05bmz3enh8 |      0 |      7 |     17 |     36 |     53 |   113 | 2020-12-05 10:34:21 |  4.1947 |  3.944651267529099 |
| Endless, Nameless                    | 7vtm1rq16hh3xch  |      0 |      0 |      3 |     16 |     24 |    43 | 2020-07-19 21:44:55 |  4.4884 |  3.922610019336613 |
| With Those We Love Alive             | 445d989vuwlh4cvz |      0 |      4 |     12 |     27 |     39 |    82 | 2020-10-15 10:22:01 |  4.2317 |  3.910424413070744 |
| Necromancer                          | b36l51ogn147x0iv |      0 |      0 |      0 |      1 |     23 |    24 | 2021-01-15 15:36:42 |  4.9583 |  3.909982359153481 |
| 9:05                                 | qzftg3j8nh5f34i2 |      3 |     15 |     94 |    234 |    124 |   470 | 2020-12-22 08:10:55 |  3.9809 | 3.9008960316566395 |
| The Lurking Horror                   | jhbd0kja1t57uop  |      0 |      2 |      9 |     41 |     29 |    81 | 2021-01-08 17:17:04 |  4.1975 | 3.8913952116851656 |
| Alias 'The Magpie'                   | yspn49v69hzc8rtb |      0 |      0 |      5 |     18 |     24 |    49 | 2020-12-01 09:10:52 |  4.2245 | 3.8903237408983813 |
| Junior Arithmancer                   | pw1rbjt1t4n4n87s |      0 |      0 |      0 |     15 |     20 |    38 | 2021-01-15 13:12:53 |  4.2105 | 3.8878657396002168 |
| Eternal                              | y8k6tys4950iowdk |      0 |      0 |      1 |      1 |     23 |    25 | 2021-01-15 01:37:45 |  4.8800 |  3.881494801132717 |
| To Hell in a Hamper                  | 6d9dfn2akcrlq1bu |      0 |      1 |     16 |     50 |     31 |    98 | 2020-11-22 02:10:24 |  4.1327 | 3.8784924030584347 |
| Midnight. Swordfight.                | 2cuwjlvpybg8oaf0 |      1 |      1 |      8 |     17 |     31 |    64 | 2021-01-15 00:08:31 |  3.9063 |  3.871600146459074 |
| Ground Zero                          | 6iekonqhhdzswyf8 |      0 |      0 |      0 |      1 |     22 |    23 | 2021-02-02 09:29:44 |  4.9565 | 3.8708812384472084 |
| Known Unknowns                       | ajf5z3ue5mtj948l |      0 |      5 |      0 |     12 |     29 |    46 | 2021-01-03 01:29:29 |  4.4130 | 3.8592405407298522 |
| Weird City Interloper                | wrt29d4nlm71udll |      0 |      0 |      5 |     14 |     23 |    42 | 2020-12-05 23:57:02 |  4.4286 |  3.856230735022758 |
| Alabaster                            | b2g8je1xxtqzei4u |      3 |      1 |     17 |     50 |     39 |   112 | 2020-11-18 23:20:28 |  4.0268 |  3.854150464190091 |
| The Mulldoon Legacy                  | k6yq5koj2zjzstpt |      0 |      1 |      4 |      8 |     25 |    38 | 2019-12-31 20:37:23 |  4.5000 | 3.8532809267102452 |
| The King of Shreds and Patches       | 9ntef9expou18abv |      0 |      3 |      5 |     31 |     26 |    65 | 2020-12-26 19:30:29 |  4.2308 |   3.85303309691039 |
| Taco Fiction                         | 2ej7ntbmoit9ytvy |      0 |      0 |     13 |     56 |     23 |    92 | 2021-01-12 16:42:52 |  4.1087 | 3.8512816490967694 |
| Worldsmith                           | mlcp0rjb34vnitau |      1 |      0 |      0 |      2 |     24 |    27 | 2020-06-05 22:17:47 |  4.7778 |   3.84303940591349 |
| Will Not Let Me Go                   | 67r2qc21m5nzexv1 |      2 |      0 |      1 |     11 |     26 |    40 | 2020-12-14 02:16:54 |  4.4750 |  3.842249425371991 |
| All Things Devours                   | 5e23lnq25gon9tp3 |      1 |      3 |     11 |     30 |     33 |    78 | 2020-05-23 17:46:41 |  4.1667 | 3.8360311147021044 |
| Gun Mute                             | xwedbibfksczn7eq |      0 |      3 |     25 |     66 |     35 |   129 | 2020-11-21 00:08:18 |  4.0310 | 3.8311079284693683 |
| Chlorophyll                          | fylzkxxyxjvoya6  |      0 |      0 |      3 |     21 |     19 |    44 | 2020-09-25 06:56:49 |  4.2727 |  3.829035769979025 |
| Shade                                | hsfc7fnl40k4a30q |     12 |     16 |     70 |    153 |    114 |   370 | 2020-11-23 21:15:17 |  3.8811 |   3.82696866838897 |
| Oppositely Opal                      | z3scyumvgsr75blm |      0 |      0 |      3 |     25 |     18 |    46 | 2021-01-15 23:15:29 |  4.3261 | 3.8233298592219636 |
| Creatures Such As We                 | 8l9cdcd1tbt77hfl |      2 |      2 |     11 |     23 |     34 |    72 | 2021-01-03 02:03:01 |  4.1806 |  3.817346556542389 |
| Death Song                           | g5wr50m23zv43ov3 |      0 |      0 |      0 |      0 |     21 |    21 | 2021-01-15 15:37:00 |  5.0000 | 3.8172670539909834 |
| Treasures of a Slaver's Kingdom      | 8upuvdnsk4sho6ac |      1 |      2 |      0 |     10 |     25 |    38 | 2020-09-24 16:15:37 |  4.4737 | 3.8153849493843297 |
| Bogeyman                             | ltwvgb2lubkx82yi |      0 |      1 |     12 |     15 |     28 |    57 | 2021-01-15 10:51:44 |  4.1754 | 3.8118836080270078 |
| Harmonia                             | bkyia4k48od1ila  |      0 |      0 |      9 |     24 |     22 |    55 | 2020-12-19 22:05:10 |  4.2364 | 3.8080944546851656 |
| Augmented Fourth                     | cpwktis6qwh9ydn8 |      0 |      1 |      6 |     32 |     20 |    59 | 2020-07-05 23:57:59 |  4.2034 |  3.807144323936464 |
| Brain Guzzlers from Beyond!          | f55km4uutt2cqwwz |      0 |      2 |      5 |     31 |     21 |    59 | 2020-12-12 20:31:10 |  4.2034 | 3.8024824838187596 |
| Galatea                              | urxrv27t7qtu52lb |      9 |     17 |     52 |    118 |     92 |   288 | 2021-01-17 06:15:10 |  3.9271 | 3.8004092603459734 |
| Aisle                                | j49crlvd62mhwuzu |      2 |     18 |     56 |    130 |     72 |   278 | 2020-12-01 14:45:25 |  3.9065 | 3.7878579336505074 |
| Christminster                        | fq26p07f48ckfror |      2 |      3 |      9 |     34 |     30 |    78 | 2020-04-25 03:15:32 |  4.1154 |   3.78575928355936 |
| Ad Verbum                            | xi4s5ne9m6w821xd |      0 |      5 |     18 |     76 |     26 |   127 | 2020-10-14 13:21:47 |  3.9213 |  3.784856254762262 |
| Eric the Unready                     | 3q9hg2onqjftx5vi |      0 |      1 |      1 |     13 |     19 |    34 | 2020-07-17 17:24:18 |  4.4706 |  3.776690994042066 |
| Kerkerkruip                          | f7zdhxmiraht53d1 |      0 |      0 |     12 |     26 |     22 |    60 | 2020-09-04 14:08:04 |  4.1667 | 3.7759931804128026 |
| Bee                                  | 8pe83e92v4nvabic |      0 |      2 |     10 |     26 |     24 |    62 | 2020-12-25 04:31:19 |  4.1613 | 3.7743386896092797 |
| Wishbringer                          | z02joykzh66wfhcl |      0 |      3 |     20 |     37 |     30 |    93 | 2020-12-17 12:12:12 |  3.9140 | 3.7673576412499705 |
| Jigsaw                               | 28uhmejlntcbccqm |      0 |      6 |     10 |     28 |     30 |    74 | 2020-12-05 11:20:18 |  4.1081 |  3.766367101480138 |
| Spellbreaker                         | wqsmrahzozosu3r  |      0 |      1 |      8 |     12 |     23 |    45 | 2020-12-17 07:34:00 |  4.2000 | 3.7539912688908177 |
| A Beauty Cold and Austere            | y9y7jozi0l76bb82 |      0 |      0 |      3 |     16 |     17 |    36 | 2020-12-04 20:09:54 |  4.3889 | 3.7507317588967997 |
| Cactus Blue Motel                    | 7e699ifb6u3767yr |      1 |      2 |      8 |     30 |     23 |    64 | 2020-09-23 16:44:57 |  4.1250 | 3.7470249287638593 |
| Leather Goddesses of Phobos          | 3p9fdt4fxr2goctw |      0 |      1 |     11 |     26 |     21 |    64 | 2021-01-10 23:06:44 |  3.8125 | 3.7398943954353783 |
| Foo Foo                              | ec6x9y8qcmsrxob9 |      0 |      1 |      3 |     21 |     17 |    42 | 2020-10-07 19:01:48 |  4.2857 | 3.7396804999214064 |
| Hunger Daemon                        | 6f1j5et0lguk2fol |      0 |      0 |      9 |     28 |     17 |    54 | 2020-11-16 05:52:07 |  4.1481 |  3.729498214812209 |
| Sorcerer                             | lidg5nx9ig0bwk55 |      0 |      1 |      5 |     28 |     16 |    51 | 2020-12-17 07:33:47 |  4.0980 | 3.7274013385863625 |
| The Dreamhold                        | 3myqnrs64nbtwdaz |      2 |      3 |     38 |     73 |     35 |   151 | 2021-01-17 06:14:32 |  3.9007 |  3.723929128006555 |
| Rematch                              | 22oqimzgf8snv002 |      1 |      0 |     18 |     36 |     23 |    78 | 2020-09-24 17:58:39 |  4.0256 |  3.719708764323183 |
| Zozzled                              | 436g2gu94kxin4x7 |      0 |      0 |      2 |     13 |     16 |    31 | 2020-11-09 23:02:58 |  4.4516 | 3.7139478351312505 |
| De Baron                             | weac28l51hiqfzxz |      4 |      7 |     33 |     63 |     44 |   153 | 2020-12-30 01:09:07 |  3.8497 |  3.709843708898226 |
| Nightfall                            | 3a4kqs374jqu2li6 |      0 |      1 |      8 |     28 |     17 |    54 | 2020-10-26 06:19:59 |  4.1296 |  3.709426944233507 |
| Dual Transform                       | xfezh9wz188ihlel |      0 |      4 |     18 |     49 |     22 |    93 | 2020-12-25 22:27:11 |  3.9570 | 3.6999989978325183 |
| So Far                               | rcrihauxixy48svr |      2 |      2 |     11 |     29 |     25 |    69 | 2020-10-14 19:42:24 |  4.0580 |  3.699598612381056 |
| Delightful Wallpaper                 | jf4rk3cvmlajhl2r |      0 |      0 |     16 |     38 |     17 |    71 | 2020-12-24 01:41:58 |  4.0141 |  3.697176261090644 |
| For a Change                         | t61i5akczyblx2zd |      2 |      4 |     24 |     43 |     32 |   106 | 2020-07-20 01:33:27 |  3.9057 |  3.694976458693648 |
| Innkeeper                            | 7fpb4ud19706he0  |      0 |      0 |      1 |      0 |     19 |    20 | 2021-01-17 03:52:56 |  4.9000 | 3.6937570901037353 |
| my father's long, long legs          | u6urdbmp6pdv6lk1 |      2 |      1 |     24 |     51 |     25 |   103 | 2020-12-28 02:54:11 |  3.9320 |  3.691738742059481 |
| You Will Select a Decision           | 5u4tg8c3n8wh590o |      1 |      1 |      8 |     27 |     19 |    56 | 2020-05-18 21:09:55 |  4.1071 | 3.6902646976844187 |
| The Axolotl Project                  | grmj2pkmo37x3fzs |      0 |      1 |      5 |     11 |     19 |    36 | 2020-06-12 12:58:31 |  4.3333 |  3.689192028351614 |
| Absence of Law                       | keqvw9c8p73wzizf |      0 |      1 |      3 |      7 |     19 |    35 | 2020-10-23 09:55:57 |  3.8286 | 3.6862235153898215 |
| Hunter, in Darkness                  | mh1a6hizgwjdbeg7 |      2 |      5 |     23 |     55 |     29 |   115 | 2020-11-27 15:09:24 |  3.8783 | 3.6856584969382498 |
| Choice of Robots                     | zflc6mnml1vqgk2s |      0 |      1 |      1 |     10 |     17 |    29 | 2020-10-14 22:56:47 |  4.4828 |  3.684382520500527 |
| Alpha Wolf                           | nndvsu896h06royv |      0 |      0 |      0 |      1 |     18 |    19 | 2021-01-15 15:37:33 |  4.9474 |  3.681491643300928 |
| Three-Card Trick                     | afy6ej5cn9hof20m |      0 |      1 |      9 |     17 |     19 |    46 | 2020-11-16 04:26:56 |  4.1739 | 3.6753599288965257 |
| Sub Rosa                             | 73nvz9yui87ub3sd |      0 |      0 |      4 |     11 |     16 |    31 | 2020-11-12 19:59:31 |  4.3871 |  3.657190986476062 |

**Comment by qdacsvx** [comment]
Changing the scoring function will change how users (should) interpret ratings. Averaging is simple. Good luck explaining starsorting to a non-technical author who is frustrated by their game's ranking and doesn't understand why their game is ranked like it is.

**Comment by kpeamon** [comment]
If you implement the algorithm, please keep the simple average too. They could be called:
"sort by average rating"
and
"sort by weighted average"

You may even add "(recommended)" to the weighted average but please keep the true average. It has a lot of value, especially when it is combined with e.g. "#ratings:3-" or something like that.

No algorithm is perfect, they are all based on assumptions that are never 100% correct. There are lots of examples of such algorithms which give inappropriate estimations in many situations. Just as an example, in your full table of results above, the algorithm comes to the conclusion that all the games (except Counterfeit Monkey at no.1) in top 100 are overrated. Thus their weighted average is below their average rating. I find it quite unlikely that all games in top 100 (except the best) are overrated. It would seem much more likely, that some were overrated and some were underrated.  The IFDB 100 has the same problem.

I am sure these algorithms have value, but they all have drawbacks too, so please keep the simple average too.

**Comment by dfabulich** [comment]
I've got a PR open to implement sorting by starsort. It's pretty tricky, and anybody with familiarity with statistics or data science would be welcome to take a look. https://github.com/iftechfoundation/ifdb/pull/71
