### ISSUE TITLE
Link to intfiction.org

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#173]
IFDB should link to intfiction.org

_Originally posted by @dougo in https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/142#issuecomment-789241715_

**Comment by dfabulich** [comment]
I think maybe this would be a collection of links…?

* intfiction forum
* Planet IF
* IF Wiki 
 
… others? (Maybe IF Archive? But we already link to IF Archive all over IFDB in individual game listings)

**Comment by fos1** [comment]
An excellent idea.

**Comment by qdacsvx** [comment]
Some individuals who are members of ifdb are banned from [intfiction](https://intfiction.org/tag/ifdb). For those individuals it appears to be discriminatory to present intfiction as the official forum of ifdb. Should ifdb ban/censor people at one remove?

The material situation of ifdb is different to intfiction. ifdb links to games it doesn't host them; if a game contains offensive content the idiom is to add a content warning. On intfiction, comments are hosted by intfiction; if a comment contains offensive content the idiom is to suppress the comment and to ban the commentor for persistent offenses.

This difference, amongst others, means that different policies in the terms of service and the code of conduct are appropriate for ifdb compared to intfiction.

I find it concerning that debates about ifdb policy held on intfiction will not take into account the relevant differences conflating policies appropriate for intfiction with policies appropriate for ifdb.

**Comment by PatientRock** [comment]
IntFiction and IFDB are now under the purview of the Interactive Fiction Technology Foundation. These two websites are not unrelated.

**Comment by alice-blue** [comment]
Where would you want the links to go?

**Comment by dfabulich** [comment]
Off the top of my head, I'd suppose we could add an "Other Resources" section to the home page side pane?

**Comment by qdacsvx** [comment]
It will be easier to find them on a separate links page if there is a 'links' link in the top bar. If I'm new to interactive fiction what are all these web links? On a links page a paragraph describing each link will help me.

**Comment by alice-blue** [comment]
Working on this.
