### ISSUE TITLE
Link to Code of Conduct in more places

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#187]
We have a Code of Conduct linked in the site footer, but I think we could stand to add links in more places.

* /newuser
* When posting/editing a review
* When flagging a review

… other places?

**Comment by alice-blue** [comment]
I created a pull request to link to the Code of Conduct on the review guidelines page (which is linked from the page for writing a review). Is this enough, or do we also want a link on the review page itself?

**Comment by dfabulich** [comment]
My intuition is that we'd want the link to be more visible than that. I'd like someone posting a review to see clearly that we have a code of conduct, that we call it a "code of conduct." (That's the spirit in which I filed this issue.)
