### ISSUE TITLE
It's still too easy to delete a user

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#188]
The moderator action links on a user look like this:

![image](https://user-images.githubusercontent.com/96150/110518733-54855600-80c1-11eb-9482-adff1d7ee3f2.png)

But if you misclick on "Delete," the user is gone in an instant, with no opportunity to undo.

There should be an "are you sure?" prompt if you click on that.

**Comment by Durafen** [comment]
Something like [this](https://github.com/iftechfoundation/ifdb/pull/57) can do the trick.

**Comment by dfabulich** [comment]
We put in an "are you sure?" prompt at some point.
