### ISSUE TITLE
The stylesheet gallery is really, really slow

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#198]
https://ifdb.org/styles?gallery attempts to load Zork I in 20 iframes with 20 different CSS stylesheets. It takes a full minute to load!

**Comment by dfabulich** [comment]
I can't even reproduce the issue in local dev. The iframes all just error out, for some reason.

**Comment by curiousdannii** [comment]
Is there any value in keeping stylesheets around that are used by only 1 or 2 people?

**Comment by dfabulich** [comment]
I've filed getting rid of it as #199.

**Comment by dfabulich** [comment]
This performance bug is caused by #223. Each iframe is spending multiple seconds loading personalized recommendations, with no caching.

Normally you can workaround #223 by logging out, but it doesn't make sense to use the stylesheet gallery while logged out.

One plausible hack would be to disable personalized recommendations when the page is being loaded in an iframe…?

**Comment by dfabulich** [comment]
I've checked that into main. The gallery is still kinda pokey, but it shows _something_ in a few seconds, as opposed to minutes. The fix will deploy to ifdb.org in the next major rollout.
