### ISSUE TITLE
Ugly searchGo parameters in the URL bar when you do a search

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#209]
Go to the home page, click in the search bar in the header, and do a search for `test`

The URL you'll arrive at is:

```
https://ifdb.org/search?searchbar=test&searchGo.x=0&searchGo.y=0
```

Those ugly `searchGo.x` and `searchGo.y` parameters shouldn't be there.

**Comment by Durafen** [comment]
This one is a controversy,  It's looking better for some pages with long texts.
IMHO I would make the change (or add URL parameter for it), and make an intfiction poll to gather users opinions.
