### ISSUE TITLE
Hide "Can't find it?" on browse pages

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#212]
IFDB searches have boxes in the upper right:

> **Can't find it?**
> If the game you're looking for isn't in our database yet, you can help improve IFDB by [adding a new listing](https://ifdb.org/editgame?id=new) yourself.

> **Bookmark this search**
> If you think you might want to repeat this search in the future, you can save the search parameters simply by bookmarking this page (adding it to your "favorites") in your browser.

Those boxes don't seem necessary/useful when you click Browse.

https://ifdb.org/search?browse

**Comment by curiousdannii** [comment]
The Can't find it? one seems okay, but the bookmark this search should definitely go.

**Comment by brirush84** [comment]
I thought you were suggesting removing it for all searches, but I see you just mean browse. I never use that link from the browse page, and never bookmark searches under any circumstances.

**Comment by alice-blue** [comment]
Based on discussion elsewhere, it seems like we are trying to make some of the links from the side panel of the home page more discoverable in other places.

[In the responsive homepage thread](https://github.com/iftechfoundation/ifdb/pull/85#issuecomment-803251058), @dfabulich, you say it makes sense to have a "create a game" link on the browse page, and that's what this "Can't find it?" box basically is--a link to create a game entry. Is it just the "Can't find it" wording you don't like?

As for the search bookmarks--maybe someone wants to bookmark the version of the "browse" page that always shows the latest games, for instance? https://ifdb.org/search?sortby=pnew&searchfor=&browse=1 Maybe it's not necessary to have that tip there, but it's not useless, either.

I do wonder if we ought to link to the "10 random games" page from here, though.

**Comment by dfabulich** [comment]
Good point! I hadn't connected those two thoughts together. I think it's the "Can't find it" wording in this case… I think it _does_ make sense to link to "create a game."
