### ISSUE TITLE
Link to "Create a Poll" when browsing/searching for polls

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#227]
https://ifdb.org/search?browse&poll&sortby=new

This page should have a link to create a poll. See also #226

**Comment by dfabulich** [comment]
Seems like the same should apply to browsing/searching lists, competitions, and clubs.

**Comment by alice-blue** [comment]
Before I go on to add similar links for lists, competitions, etc.--does anyone have thoughts on the following:

This is modeled after the tip boxes that show up when you Browse/Search games, so like those, it shows up (1) when you are browsing and (2) when you are searching and there are search results.

It does not show up when you click to search polls, and have not entered any search terms (the search tips page). I'm not sure if we wanted something there as well, and if so, what (this same tip box? A text link within the search tips?)
