### ISSUE TITLE
Remove/replace TADS.org link in footer

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb-suggestion-tracker#235]
The footer of the website includes a link to TADS.org

Is there a reason to associate the website TADS, now that it is on its own domain?

Perhaps https://iftechfoundation.org/ would be a better fit?

**Comment by fos1** [comment]
I don't see any reason to remove the TADS.org link in the IFDB footer. MJR
developed and maintained IFDB for many years. TADS is still one of the best
IF development systems available. TADS.org is still very relevant.

**Comment by salty-horse** [comment]
Relevant, sure. But is there any reason to highlight it and not of any of the other authoring systems?

It's fine if it remains out of respect for the origins of IFDB. At the moment, it feels like a leftover from the transition to the new domain.

**Comment by dfabulich** [comment]
I'm inclined to leave it out of respect for the origins of IFDB. Maybe we'll pull it in a few years…?

**Comment by alice-blue** [comment]
Another option (in a few years?) would be to link to tads.org on a separate page--an "about" page discussing the history/origins of IFDB.

**Comment by tobiasvl** [comment]
There's also the "IF Links" aside-box on the main page...

And I think it would make sense to have a link to IFTF somewhere (unless I missed one).

My suggestion would be to put a link to IFTF in the footer, and also possibly (and non-sentimentally and disrespectfully) move the TADS link to the "IF Links" box (and consider adding Inform/Twine/others as well?).

**Comment by erkyrath** [comment]
I want to bump this, given the forum discussion here: https://intfiction.org/t/monetising-the-ifdb/69876

The other IFTF sites now have an IFTF logo and a line like "The Archive is managed by the Interactive Fiction Technology Foundation. It is funded by the donations of IF supporters like you." (See: https://ifarchive.org , https://ifcomp.org , https://twinery.org )

In addition, I've added a "Donate via Paypal" button to https://ifarchive.org . I think this would be appropriate for IFDB as well. The HTML for this is simple:

```
<form action="https://www.paypal.com/donate" method="post" target="_top">
<input type="hidden" name="hosted_button_id" value="2CZJEA3PXM3QS" />
<input class="Donate" type="submit" value="Donate with PayPal">
</form>
```

The ID value `2CZJEA3PXM3QS` is set up on Paypal to display like this:

![snap](https://github.com/user-attachments/assets/6af693c5-5486-43d1-999f-e90d368f4eb3)

(As treasurer, I track how much money comes in through each Paypal link. To be clear, there's no notion of limiting IFDB's budget to donations through this button! It's just a way for us to get an idea of what services are popular.)

**Comment by samplereality** [comment]
> The other IFTF sites now have an IFTF logo and a line like "The Archive is managed by the Interactive Fiction Technology Foundation. It is funded by the donations of IF supporters like you."

100% support the idea of a footer on IFDB like this, plus a Paypal link for donations.

**Comment by dfabulich** [comment]
Adding an IFTF branding is #167, and I'm working on it in https://github.com/iftechfoundation/ifdb/pull/306.

I've also filed a PR to remove the TADS.org link in https://github.com/iftechfoundation/ifdb/pull/307
