### ISSUE TITLE
Moderators need a way to edit reviews/comments

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#26]
Apropos #25, users can edit their own reviews and comments, but moderators/administrators can't edit other people's reviews/comments, not even to add a spoiler tag.

**Comment by dfabulich** [comment]
A workaround just occurred to me: administrators are allowed to impersonate ("log in as") other users; each user is allowed to edit their own reviews/comments. As long as we have a policy that moderators/admins are supposed to leave a note when they use impersonation to edit a post, I think that should be good enough to start with.

**Comment by Durafen** [comment]
I have finished implementing this feature in [pr 25](https://github.com/iftechfoundation/ifdb/pull/25).
Please test and let me know if fixes needed.
