### ISSUE TITLE
Make shadowbanned users' votes not appear on polls

### ISSUE THREAD

**Issue by brirush84** [iftechfoundation/ifdb-suggestion-tracker#282]
This may already be implemented, but I don't think so.

**Comment by Keltena** [comment]
Hidden votes still cause polls to be listed on /viewgame and /allpolls pages. (Example: [/viewgame](https://ifdb.org/viewgame?id=lq1vuafjav88xoya), [/allpolls](https://ifdb.org/allpolls?game=lq1vuafjav88xoya); compare [the poll itself](https://ifdb.org/poll?id=2k8uo97ycddlvunl).)
