### ISSUE TITLE
User profiles should sort the author's games by "highest rated"

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#289]
https://ifdb.org/showuser?id=4onqcn9pq2wtd3vb shows all of Emily Short's games, sorted alphabetically. Instead, we should sort it by "highest rated" (star sort), with a drop-down to sort it in other ways.

**Comment by lkcampbell** [comment]
@dfabulich, this is a side observation but it may affect the final UI on this. I can't figure out why we have pages like  `alllists` and `allpolls` when we could just link to `search author:Emily Short`, for example. I think these pages are even out of sync with the `search` page. Certainly the sort lists look different. Maybe we should just run everything we can through `search`. Unless you can see something different that I am not seeing.

Here's an alternative idea which might be easier and more consistent with the current UI. Provide the top five (maybe more?) star sorted games in the section and put a link at the bottom that goes to `search author:<author>`. Then, all of the sorting can be handled by the existing `search` page.

What do you think?

**Comment by dfabulich** [comment]
I'd be down for that.

**Comment by alice-blue** [comment]
> Here's an alternative idea which might be easier and more consistent with the current UI. Provide the top five (maybe more?) star sorted games in the section and put a `See all of this member's games` link at the bottom that goes to `search author:<author>`. Then, all of the sorting can be handled by the existing `search` page.

Right now, authors have the option to link games to their profile or not. They might appreciate having that option. Also, it's possible for more than one author to have the same name (e.g. Robin Johnson).

```
Linking a game to your profile
If you're the author of a game listed in IFDB, you can link it to your profile. This will automatically include the game in a list of authorship credits on your public profile page, and it will include a link to your profile next to your name as it appears in the byline on the game's overview page.

To link a game to your profile, follow these steps:

Go to the game's main page
Click "Edit this page" at the bottom of the game page
In the Author field, insert your profile ID (the TUID) in {curly braces} after your name. For example, Arthur Dent {0x098109klasd09313k}. You can find the TUID on your main profile page.
Save your changes. A link to your profile will now appear on the game's page after your name in the byline, and the game will be listed in your profile's authorship section.
Unlinking a game
To remove a profile link from a game, just edit the game's listing and remove your profile ID (the {xxxxxxx} code) from the Author field.
```

**Comment by lkcampbell** [comment]
> Right now, authors have the option to link games to their profile or not. They might appreciate having that option.

How does this change affect an author's choice to link, or not link, their games to their profile?

> Also, it's possible for more than one author to have the same name (e.g. Robin Johnson).

That's a good point. I can add an authorid search parameter to the game search to address that scenario. It doesn't even have to be documented since your average user isn't going to want to search by an arbitrary author id anyway.

Side note: I'm surprised that the TUID search parameter for the game search page *is* documented since, again, a user isn't typically going to know the TUID is unless they already looked up the game first. I can add that parameter to polls and lists, and completely replace `alllists and `allposts`, but I will file a separate tech issue on the IFDB repo to do that.

**Comment by alice-blue** [comment]
> > Right now, authors have the option to link games to their profile or not. They might appreciate having that option.
> 
> How does this change affect an author's choice to link, or not link, their games to their profile?

I thought you were suggesting listing a given author's top 5 (by rating) games on their profile, and linking to a search for the rest.   Maybe I misunderstood. If not...what if the author wants a different set of games on their profile than their top 5? Maybe they want more than 5, or maybe one of the top 5 is one they don't want on their profile at all.

**Comment by lkcampbell** [comment]
> Right now, authors can adjust which games appear on their profile by linking or unlinking the games. I thought you were suggesting a different way of choosing which games appear: by automatically listing a given author's top 5 (by rating) games on their profile, and linking to a search for the rest.

I understand what you are asking about now. This will not affect linking and unlinking games to the profile, it only affect how those links are displayed. It can't display links that don't exist.
