### ISSUE TITLE
Don't display all of Cragne Manor's authors in lists

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#292]
Cragne Manor has 84 authors, so it takes up a bunch of space when it shows up in search results (which it often does). We should abbreviate its appearance somehow.

![image](https://user-images.githubusercontent.com/96150/114289431-a9075280-9a2c-11eb-937a-83792d9a0d92.png)

There are a number of other collaboration games with many authors, but none of them are _quite_ so enormous.

https://ifdb.org/search?searchfor=l+math+adventure

> [L: A Mathemagical Adventure](https://ifdb.org/viewgame?id=lu8plxd16bms5a4r)
> by members of the Association of Teachers of Mathematics co-ordinated by Richard Phillips, and including Derek Ball, Tony Corbett, David Rooke, Heather Scott, Alan Shaw, Margaret Stevens, Ruth Townsend, Jo Waddingham, Roger Waddingham, John Warwick, Alan Wigley, John Wood, and David Wooldridge.

![image](https://user-images.githubusercontent.com/96150/114289423-9ab93680-9a2c-11eb-8714-e8d504ef8765.png)

https://ifdb.org/search?searchfor=pick+up+the+phone+booth

> [Pick Up the Phone Booth and Aisle](https://ifdb.org/viewgame?id=4gb36vjo20qpvxty), by David Dyte, Steve Bernard, Dan Shiovitz, Iain Merrick, Liza Daly, John Cater, Ola Sverre Bauge, J. Robinson Wheeler, Jon Blask, Dan Schmidt, Stephen Granade, Rob Noyes, and Emily Short (2001)

![image](https://user-images.githubusercontent.com/96150/114289418-8e34de00-9a2c-11eb-8a9d-fd4815ef7f3a.png)

**Comment by alice-blue** [comment]
The list of Cragne Manor authors also appears on the Anchorhead page, under "Referenced in."

**Comment by andrewschultz** [comment]
I suspect you've already thought of something like this, but just to make sure: my guess of how to implement something like this might be to have a checkbox to the side saying "main author?"

So Cragne Manor would be folded into "Ryan Veeder, Jenni Polodna et al."

That'd be my perspective as a user. I'd think we'd want to see all the authors on the main page, of course.

**Comment by curiousdannii** [comment]
Would go well with #31. Ryan and Jenni could be marked as both editors and the main authors.

**Comment by lkcampbell** [comment]
> So Cragne Manor would be folded into "Ryan Veeder, Jenni Polodna et al."

I like this idea. A collapsed "et al." and an expanded (i.e. normal) version. Similar functionality to code folding in a code editor. An arrow icon toggles between collapsed and expanded views. Then, for every page that a game listing appears, we decide if the default view for a multi-author game is `expanded` or `collapsed`. For example, on the `viewgame` the default would be `expanded` but on `showuser` the default would be `collapsed`

**Comment by alice-blue** [comment]
In games where some of the authors are marked "main" authors, you could give the number ("Author A, Author B, and N more authors"), and make the "N more authors" clickable to show the rest.

**Comment by lkcampbell** [comment]
I'll take this one next.

**Comment by lkcampbell** [comment]
So here's my first shot at this, keeping things as simple as possible, using only the `details` and `summary` html elements. No CSS or Javascript. This is from the `showuser` page (a.k.a. Profile).

Collapsed:
![Screen Shot 2021-04-12 at 4 20 20 PM](https://user-images.githubusercontent.com/1774931/114474530-48525400-9bab-11eb-97fc-b1e80d8b1dcd.png)

Expanded:
![Screen Shot 2021-04-12 at 4 20 36 PM](https://user-images.githubusercontent.com/1774931/114474568-5bfdba80-9bab-11eb-9599-c43d1e51066e.png)

**Comment by dfabulich** [comment]
How would the code know which authors to show above the fold? e.g. for Alabaster, I think I'd write it as "Emily Short et al." but I don't know how the code could know that.

Regarding that, I have what may be a controversial suggestion: literally hard-code this setting, and use it _only_ for Cragne Manor. Why? Because even the second longest author list, for "L: A Mathemagical Adventure," is kinda long, but it's not _too_ visually overwhelming. Cragne Manor's author list is 1,251 letters long, 23 lines on my screen; L's author list is "only" 292 letters long, six-lines on my screen, which feels fine. Alabaster is only three lines; practically nothing!

Perhaps some day we'll get another game with roughly as many authors as Cragne Manor, and we can put in another hack in that case, or, more likely, we'll get around to working on #31 and we'll use that data to elegantly collapse author lists, but for now, simply putting in a hack for _just_ Cragne Manor feels like the right answer to me.

For the record, here's the MySQL query I used to find games with long author fields:

```sql
select id, title, author, length(author) from games order by length(author) desc limit 20 \G
```

<details><summary>and here are the results</summary>

```
*************************** 1. row ***************************
            id: 4x7nltu8p851tn4x
         title: Cragne Manor
        author: Ryan Veeder, Jenni Polodna, Adam Whybray, Adri, Andrew Plotkin, Andy Holloway, Austin Auclair, Baldur Br�ckner, Ben Collins-Sussman, Bill Maya, Brian Rushton, Buster Hudson, Caleb Wilson, Carl Muckenhoupt, Chandler Groover, Chris Jones, Christopher Conley, Damon L. Wakes, Daniel Ravipinto, Daniel Stelzer, David Jose, David Petrocco, David Sturgis, Drew Mochak, Edward B, Emily Short, Erica Newman, Feneric, Finn Rosenl�v, Gary Butterfield, Gavin Inglis, Greg Frost, Hanon Ondricek, Harkness Munt, Harrison Gerard, Ian Holmes, Ivan Roth, Jack Welch, Jacqueline Ashwell, James Eagle, Jason Dyer, Jason Lautzenheiser, Jason Love, Jeremy Freese, Joey Jones, Joshua Porch, Justin de Vesine, Justin Melvin, Katherine Morayati, Kenneth Pedersen, Lane Puetz, Llew Mason, Lucian Smith, Marco Innocenti, Marius M�ller, Mark Britton, Mark Sample, Marshal Tenner Winter, Matt Schneider, Matt Weiner, Matthew Korson, Michael Fessler, Michael Gentry, Michael Hilborn, Michael Lin, Mike Spivey, Molly Ying, Monique Padelis, Naomi Hinchen, Nate Edwards, Petter Sj�lund, Q Pheevr, Rachel Spitler, Reed Lockwood, Reina Adair, Riff Conner, Roberto Colnaghi, Rowan Lipkovits, Sam Kabo Ashwell, Scott Hammack, Sean M. Shore, Shin, Wade Clarke, Zach Hodgens, Zack Johnson
length(author): 1251
*************************** 2. row ***************************
            id: lu8plxd16bms5a4r
         title: L: A Mathemagical Adventure
        author: members of the Association of Teachers of Mathematics co-ordinated by Richard Phillips, and including Derek Ball, Tony Corbett, David Rooke, Heather Scott, Alan Shaw, Margaret Stevens, Ruth Townsend, Jo Waddingham, Roger Waddingham, John Warwick, Alan Wigley, John Wood, and David Wooldridge.
length(author): 292
*************************** 3. row ***************************
            id: kahycddsc66eq909
         title: Quest for Arete
        author: Dene Grigar, Judith Pintar, Jazz Jackson, Katya Farinsky, Betsy Hanrahan, Elyse Mollahan, Viet Anh Nguyen, Preston Reed, David Sabrowski, Andrew Swanson, Andrew Thompson, Brandan Touhey, Craig Vesterby, Keegan Walden, Ruth Woodcock
length(author): 231
*************************** 4. row ***************************
            id: em7o99947wdhq6ew
         title: An Escape To Remember
        author: Sean Barrett, Tom Blawgus, Roger Carbol, John Cater, Ricardo Dague, Jeremy Douglass, Josh Giesbrecht, N. B. Horvath, Carl Muckenhoupt, Mark Musante, Karl Parakenings, Mordechai Shinefield, Dan Shiovitz, Lucian Smith
length(author): 215
*************************** 5. row ***************************
            id: j1tsfr4jxofavyd1
         title: Grayscale
        author: D. Fox Harrell, Pablo Ortiz, Sofia Ayala, Laurel Carney, Elizabeth Carre, Peter Downs, Chong-U Lim, Jackie Liu, Loren Sherman, Yao Tong, George Tsiveriotis, Maya Wagoner, Annie Wang, Nadia Wiwatwicha
length(author): 199
*************************** 6. row ***************************
            id: nq24rpyihbn95a3k
         title: The Corn Identity
        author: Carl Muckenhoupt, Serhei Makarov, Tama Wise, J. Robinson Wheeler, A O Muniz, Admiral Jota, Andrew Schepler, Jacqueline A. Lott, Sam Kabo Ashwell, Dan Shiovitz, John Cater, Duchess, and Mark Musante
length(author): 197
*************************** 7. row ***************************
            id: 6vej1yd9quwfm9qn
         title: Pick Up the Phone Booth and Aisle
        author: David Dyte, Steve Bernard, Dan Shiovitz, Iain Merrick, Liza Daly, John Cater, Ola Sverre Bauge, J. Robinson Wheeler, Jon Blask, Dan Schmidt, Stephen Granade, Rob Noyes, and Emily Short
length(author): 184
*************************** 8. row ***************************
            id: xrofykwwtvx686gr
         title: What Happens in Vagueness
        author: Sam Kabo Ashwell, Tom Blawgus, N.B. Horvath, Justin Larue, Jacqueline A. Lott, Michael Martin, Carl Muckenhoupt, Marius M�ller, Mark Musante, and Brian Rapp
length(author): 156
*************************** 9. row ***************************
            id: n6gtncaxbx3ztfb9
         title: Deformuseum
        author: Sophie Fruehling, Ralf Herrmann, Florian Kalenda (aka Florian Edlbauer), Max Kalus, Christof Menear, Martin Oehm, Christoph Winkler, Christian Bluemke
length(author): 150
*************************** 10. row ***************************
            id: b2g8je1xxtqzei4u
         title: Alabaster
        author: John Cater, Rob Dubbin, Eric Eve, Elizabeth Heller, Jayzee, Kazuki Mishima, Sarah Morayati, Mark Musante, Emily Short, Adam Thornton, Ziv Wities
length(author): 144
*************************** 11. row ***************************
            id: n51f64zk65y8jfqd
         title: La Aventura Espacial
        author: Juan Antonio Darder, Carlos Marqu�s, Vicente Misas, Royo, Juan Manuel Medina, Andr�s Roberto Samudio Monro, and Andr�s Roberto Samudio Monro
length(author): 140
*************************** 12. row ***************************
            id: 20f753czrlhoorfh
         title: House of Dream of Moon
        author: Admiral Jota, Sam Kabo Ashwell, Tom Blawgus, Ricardo Dague, N. B. Horvath, Carl Muckenhoupt, Marius M�ller, Jacqueline A. Lott, Mark Musante
length(author): 140
*************************** 13. row ***************************
            id: sv2ogva4urs43jwi
         title: Lancelot
        author: Christina Erskin, Joan Lamb, Neil Scrimgeour, Dicken Peeke, Nusarath Jahan, Mike Austin, Nick Austin, John Jones-Steele, and Mike Bryant
length(author): 136
*************************** 14. row ***************************
            id: 1ajyh9lns8rldsmb
         title: Wonderland
        author: David Bishop, Bob Coles, Paul Findley, Ken Gordon, Richard Huddy, Steve Lacey, Doug Rabson, Anita Sinclair, Hugh Steers and Mark Taylor
length(author): 135
*************************** 15. row ***************************
            id: md0lb2dczqayesxu
         title: Jabato
        author: Manuel Gonz�lez, Juan Antonio Darder, Carlos Marqu�s, Francisco Zarco, Andr�s Roberto Samudio Monro, and Andr�s Roberto Samudio Monro
length(author): 133
*************************** 16. row ***************************
            id: pmmrw4wjx3hw5su2
         title: La diosa de Cozumel
        author: Andr�s Roberto Samudio Monro, Andr�s Roberto Samudio Monro, Tim Gilberts, Juan Antonio Darder, Carlos Marqu�s, and Francisco Carri�n
length(author): 132
*************************** 17. row ***************************
            id: qfmo3lsen56jmu5p
         title: La Aventura Original
        author: Andr�s Roberto Samudio Monro, Andr�s Roberto Samudio Monro, Manuel Gonz�lez, Carlos Marqu�s, Vicente Misas, and Juan Antonio Darder
length(author): 131
*************************** 18. row ***************************
            id: 0oa8mv38ui956q1a
         title: Voices of Spoon River
        author: Jon Scoresby, Tim Stowell, Tom Caswell, Jared Bernotski, Marie Duncan, Marian Jensen, Jennifer Jorgensen, and Brett Shelton
length(author): 123
*************************** 19. row ***************************
            id: bta30wyz03aupg0z
         title: A�L�I�E�N: La aventura - Edici�n Especial
        author: Alpha Aventuras (Ricardo P�rez, Manuel Mill�n, Francisco J. Rold�n, Manuel I. Monge, Antonio Matiola, Francisco Picazo)
length(author): 119
*************************** 20. row ***************************
            id: iwllny7khs8s7ng1
         title: En el Anillo dorado
        author: Baltasar el Arquero (revision), Andr�s Samudio, Vicente Misas, Juan Antonio Darder, Carlos Marqu�s, Juan Manuel Medina
length(author): 118
20 rows in set (0.011 sec)

```

</details>

**Comment by lkcampbell** [comment]
> How would the code know which authors to show above the fold? e.g. for Alabaster, I think I'd write it as "Emily Short et al." but I don't know how the code could know that.

Correct, the code doesn't know how to do that. All the code does is take the comma-separated list of authors we get from the sql query and turn it into a collapsible list, with the first two authors in the list written above the fold.

They only way to affect the ordering of the list is to change it by editing the game listing.

**Comment by dfabulich** [comment]
Well, the point stands that I don't know who the "second" author for Alabaster would/should be. Emily Short was the only "editor" in this case, as I understand it.

(Of course, that's fine if we set the threshold so high that it's effectively just a Cragne Manor feature, not even applying to L:AMA.)

**Comment by lkcampbell** [comment]
> (Of course, that's fine if we set the threshold so high that it's effectively just a Cragne Manor feature, not even applying to L:AMA.)

Yup, that's what I was going to suggest. I can set the threshold at twenty-five authors. That's well below Cragne Manor's 80+ author count and enough above the 14 authors of L:AMA.

Does the UI look okay?

**Comment by curiousdannii** [comment]
Hard coding makes sense for an immediate fix. A better one can be implemented later on when authors can be marked as "main", which would be essentially to check if any are marked as main, and if so, only show them. Kerkerkruip never had the other contributors added to IFDB, but if this sort of system was implemented then it would be good to do so.
