### ISSUE TITLE
Searching author names with periods gives an error

### ISSUE THREAD

**Issue by erkyrath** [iftechfoundation/ifdb-suggestion-tracker#310]
If you look at https://ifdb.org/viewgame?id=adtwrra6bwcux97l , the author's name link is [https://ifdb.org/search?searchfor=author%3AXalavier+Nelson+Jr.](https://ifdb.org/search?searchfor=author%3AXalavier+Nelson+Jr.)

Clicking on this gets you:

```
An error occurred searching the database.
No results were found.
```

If you delete the period from the URL, it turns up Xalavier's games correctly.

**Comment by dfabulich** [comment]
My fix for this broke tag search. I rolled back that fix. https://github.com/iftechfoundation/ifdb/issues/189
