### ISSUE TITLE
"Play Online" buttton for TADS2 games (similar to glulx/zcode games) using elseifplayer

### ISSUE THREAD

**Issue by mogarithm** [iftechfoundation/ifdb-suggestion-tracker#319]
With elseifplayer, it's now possible to play TADS2 games online in the browser. 

e.g: 
Babel:
original download: https://ifarchive.org/if-archive/games/tads/Babel31.gam
elseifplayer: https://he4et.github.io/elseifplayer/#/play/https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Ftads%2FBabel31.gam

Rematch:
original download: https://ifarchive.org/if-archive/games/tads/Rematch.gam
elseifplayer: https://he4et.github.io/elseifplayer/#/play/https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Ftads%2FRematch.gam

First Things First:
original download: https://ifarchive.org/if-archive/games/tads/ftf.gam
elseifplayer: https://he4et.github.io/elseifplayer/#/play/https%3A%2F%2Fifarchive.org%2Fif-archive%2Fgames%2Ftads%2Fftf.gam

It's possible to auto-genarate the elseifplayer URL from the original ifarchive URL. It is also presumably possible to batch-upload these URLs to IFDB. But it doesn't seem to be possible for it to get a "Play Online" button, in the way glulx/zcode games do with parchment. 

There are 363 TADS2 games currently listed on IFDB. Making these playable online would greatly aid accessibility and visibility.

**Comment by curiousdannii** [comment]
I'll be adding support for TADS to Parchment very soon (it should've been done a while ago...) It's up to the IFDB team if they want to wait for that or not. Sorry.

**Comment by curiousdannii** [comment]
Hugo and TADS are now supported on iplayif.com!

However there are some pretty big bugs with the TADS 3 menus, so you may not want to enable it straight away?

**Comment by dfabulich** [comment]
Post links to the bugs?

**Comment by curiousdannii** [comment]
This is the main one I'm aware of: https://github.com/curiousdannii/parchment/issues/82

**Comment by curiousdannii** [comment]
For TADS3, IFDB will need to detect whether a storyfile is Web UI or not, as ifplayif.com will only support classic UI. There's a forum thread about how you can detect it here: https://intfiction.org/t/detect-whether-a-tads-3-file-uses-web-ui/52007

**Comment by dfabulich** [comment]
TADS and Hugo games now have Play Online buttons https://ifdb.org/viewgame?id=z5xgyw0jbt9r3ah1
