### ISSUE TITLE
There is no easy way to link to individual reviews unless they appear on the front page

### ISSUE THREAD

**Issue by brirush84** [iftechfoundation/ifdb-suggestion-tracker#32]
If you are on a game's page or a user's review page, it is difficult to find an individual link to an individual review.

**Comment by Durafen** [comment]
Added [PR 24](https://github.com/iftechfoundation/ifdb/pull/24) to add this functionality.

**Comment by qdacsvx** [comment]
Thank you Durafen.

**Comment by Durafen** [comment]
It was an easy one :)
