### ISSUE TITLE
Add "remarks from the author"

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#33]
If you're the author of a game, there's nowhere to put your general remarks about your game, e.g. "This game was fun to write because …"

Some authors have accidentally(?) reviewed their own game in order to leave these remarks, which is clearly not the right way to go about this.

**Comment by dfabulich** [comment]
This might get tricky, because we have no way of verifying that any given IFDB user is the author of a game. I get a little dizzy thinking about what it would be like to verify that…

**Comment by curiousdannii** [comment]
There's a lot of stuff from Goodreads that we could borrow. Their authors notes system is one. For example: https://www.goodreads.com/notes/4436008-james-corey?ref=rnlp

We're a small community, so we could just leave it to mods to resolve someone claiming they're being impersonated, if that ever happens.

**Comment by dfabulich** [comment]
IFDB already has this feature!

one of the options on the review page is

> **6. Special review type:**
> 
> None
> From the Author
> 
> It gives me this option regardless of whether it’s my own game (linked to my user profile) or not.
