### ISSUE TITLE
Redesign mobile viewgame page

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#335]
The mobile page looks really weird. If you login, we're showing the entire side pane ("Download" "Have you played this game?" "Playlists and Wishlists" "RSS Feed") before the cover art, title, and author.

Mobile design is inherently challenging, because it's extremely difficult to demonstrate to users that they haven't seen the whole page yet. As soon as they reach a very long section, taller than the screen is tall, users incorrectly assume that the entire rest of the page looks like that, often missing critical information.

Here's my thoughts on what a mobile design should look like, based primarily on what I see on the App Store and GPS.

**I think in some sections we'll want a "see more" link.** e.g. for the full description, we'd show just a few lines of the description, fading to transparency, with an expandable "see more" link to expand the section and see the full thing. I'm imagining we'd do that to the description, the download links, and each review. You can see examples of this on the App Store for iPhone and in the Google Play Store for Android, so it's probably a pretty reasonable approach.

1. Cover art, title, author, genre, year
2. Ratings summary: X stars (based on Y ratings), Z reviews: hyperlinked to the "Reviews" section further down the page; we'd smooth scroll down to it if you click on it.
3. Playlists and Wishlists summary: X members have played this game; it's on Y wishlists
4. If the game has a "Play Online" button, put that in here, or a big "Download" button otherwise, hyperlinked to the "Downloads" section below. (Include both side-by-side if both are available?)
5. (If logged in) "Have you played?" section
    * Rate it
    * Review it
    * Suggest similar games
    * Checkboxes: [ ] I've played it, [ ] It's on my wishlist, [ ] I'm not interested
6. "Description" with "see more" link
7. Awards
8. Downloads section (linked to from above), with a "see more" link
9. Reviews section
    * (If logged in) link to rate/write a review
    * Bar chart of reviews, average rating
    * Three reviews, with "see more" link for each
    * Read all X reviews
10. Editorial reviews, with "see more" link for each
11. News (it kinda sucks to show this so far down, but… what else could we do??)
12. Tags
13. Game Details (this section now appears _wayyy_ further down the page, but I think that's the right call)
14. If you enjoyed "Game Name":
    * Related games
        * Suggest similar
    * Recommended lists
    * Polls
15. RSS feeds

**Comment by dfabulich** [comment]
Some of what I've written here suggest that similar changes could apply to the desktop page as well:

1. Move "Playlists and Wishlists summary" out of the side pane and into the main page
2. Reorder main-page sections to match this order: Description, Awards, Member Reviews, Off-site Reviews, News, Tags, Game Details
3. Put RSS feeds all the way down in the footer

**Comment by Iniquit** [comment]
This makes a lot of sense to me! I went and took a look at Steam's mobile view as a comparison with another site that maintains a large database of games, and it follows the same general outline-- cover art, creator, and year at the top, reviews at the bottom.

They also make good use of collapsible headers (like you mentioned above), tabs, and carousels that you can swipe through horizontally on mobile.

Another thing I liked about Steam's version is that they actually have two descriptions for each game-- a short one, shown at the top of the page, and the full one, shown below.

<img width=50% src="https://user-images.githubusercontent.com/45113412/146650616-191b1610-21a5-4aa6-9a02-2a977e29c238.png"></img>
