### ISSUE TITLE
Search for tags

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb-suggestion-tracker#35]
A search which lists matching tags.

Although you can currently read through the list of IFDB's public tags, the list is rather long, on multiple pages, and it's sometimes more convenient to search directly if you have a specific tag in mind but e.g. don't know precisely how it's spelt.

It's also possible to construct a custom search using e.g. tag:furry in the search box - but this is nonobvious to new users.

The search should return the same results as for a custom tag:x search e.g. it should return multiple tags if tag:x would.

**Comment by lkcampbell** [comment]
One thing we could do is return a list of tags that match the search and make each of those tag results a hyperlink that goes to a game search for that given tag.

**Comment by lkcampbell** [comment]
Not sure. I'm assuming there will be multiple search results for tags. If you put all games matching each tag under them, that would be a lot of games potentially on a single page. And if you chose to page each list of games, you would have multiple paging elements on a single page. Seems pretty messy to me.

**Comment by dfabulich** [comment]
Right now, the easy thing to do would be to add a "Tags" tab that just shows tags in the search result. Anything else is basically "multiform search" #37, which I think will be a lot of difficult design work and tuning work to get right.
