### ISSUE TITLE
Rename "Download Links" to "Links"

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#351]
The "Downloads" section doesn't just have downloads; it has all kinds of links, to the story file, to online hints, or whatever. We should rename the section on the `viewgame` page and in the `editgame` form.

**Comment by NilsFagerburg** [comment]
What should we do with the existing *Links* section that contains a link to the game's *Web site* field and a possible link to ifwiki?
Delete it and move the contents into the new *Links* (previously *Download*) section?
I'd assume we don't want both a *Web site* field and a *Links* field on the `editgame` page so should we delete the *Web site* field and migrate the existing values into the `gamelinks` table?

**Comment by dfabulich** [comment]
We renamed it to "External Links"
