### ISSUE TITLE
Can't add game to poll using IFID

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb-suggestion-tracker#361]
Reported at [intfiction.org](https://intfiction.org/t/ifdb-games-not-found-by-ifid/56138):

> I’ve noticed that when I search for games by IFID (when trying to add them to a poll), the game title does come up, eg:
> 
> Vote => Game Title, by Game Author
> 
> but if I then click ‘Vote’ I’m told: The selected game was not found in the database. TUID does work though.
> 
> The world will probably keep spinning if this isn’t fixed, but just thought I’d report it anyway…

**Comment by patrick-brian-mooney** [comment]
Just noting that this is still happening.

**Comment by dfabulich** [comment]
I don’t reproduce this issue, but I didn’t try that hard. I tried adding Counterfeit Monkey to a poll with its IFID 7B5A779B-4653-43DB-A516-F475DDC12987 and it worked fine.

But we’ve recently found that IFIDs are a little weird, so if you can suggest an IFID that isn’t working, it’d be helpful to post that.

**Comment by patrick-brian-mooney** [comment]
Whoops, missed this while I was out of town! Sorry about that.

I was trying to add Alex Harby's *Honk* (IFID 2E670334-712D-4290-94ED-7F8E8F3A5B17) to (I think?) [this poll](https://ifdb.org/poll?id=sftgnvqzx6nv7zj5).
