### ISSUE TITLE
Click on a genre to search by genre

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb-suggestion-tracker#38]
Many games have a genre field, but mysteriously, you can't click that field to see all games of that genre. There could also be a specific search for genres.

**Comment by dfabulich** [comment]
I split "searching for genres" out into a separate issue #97.

**Comment by lkcampbell** [comment]
@qdacsvx to clarify the request:
![Screen Shot 2021-03-19 at 10 55 56 AM](https://user-images.githubusercontent.com/1774931/111823365-1b5b9b80-88a2-11eb-9aa7-f4b0715d21c5.png)

How I understand your request is the "Horror" field shown above should be a hyperlink and then when the hyperlink is clicked it should navigate to the search game page looking at genre:Horror games like this:

![Screen Shot 2021-03-19 at 11 02 45 AM](https://user-images.githubusercontent.com/1774931/111824109-fca9d480-88a2-11eb-99b1-8d67787fae28.png)

Am I understanding your request correctly?

**Comment by qdacsvx** [comment]
Yes, that looks good.

A button "Search" next to the genre is easier to use than a text link on a touch screen. Or you can use CSS to make links have an (invisible) hit area larger than merely the text.

I'm a bit concerned with making each line (e.g. date, genre...) have a search link: will it be hard to hit a specific link using a touch screen?

**Comment by lkcampbell** [comment]
I guess we could try it out and see how it works on a touch screen. I haven't done much testing with a touch screen. Are you using a phone?

**Comment by qdacsvx** [comment]
I could try it on a touch screen if you have a test page.

**Comment by lkcampbell** [comment]
If the pull request gets approved and merged in, you will be able to test it at the IFDB Dev Server before it gets deployed to the production server.

**Comment by lkcampbell** [comment]
@dfabulich please close this issue as fixed.
