### ISSUE TITLE
Suggestion: Add ifSpace.net to list of Development Systems

### ISSUE THREAD

**Issue by zacguymarino** [iftechfoundation/ifdb-suggestion-tracker#382]
Two potential routes:
1/2
> Add ifSpace.net as a development system

2/2
> Describe its shortcomings here so that the ifSpace.net developer can work to match the criteria (for future listing as dev system)

**Comment by PatientRock** [comment]
> Two potential routes: 1/2
> 
> > Add ifSpace.net as a development system
> 
> 2/2
> 
> > Describe its shortcomings here so that the ifSpace.net developer can work to match the criteria (for future listing as dev system)

Hello,

IFDB is really meant to host an exhaustive list of development platforms. Instead we recommend:

1. You submit your platform to IFWiki: https://www.ifwiki.org/Form:Software
2. You announce it on the IntFiction forums and become involved with that community: https://intfiction.org/

Thank you,

---Austin Auclair, on behalf of the IFDB moderation team.

**Comment by dfabulich** [comment]
When creating/editing a game listing, you can set the development system to anything you like, even if it doesn't appear in the provided list; just type it into the box.
