### ISSUE TITLE
Direct link to one's own reviews

### ISSUE THREAD

**Issue by russo2116** [iftechfoundation/ifdb-suggestion-tracker#395]
I could just be missing a non-obvious option, but for my own reviews, the "revise" link replaces the "more options" drop-down that allows one to get the direct url for a review.  It'd be nice if there was an easy way to get this link to share my own reviews!

**Comment by salty-horse** [comment]
Do you mean a link to all of your reviews, or a single review? Both types are supported.

e.g.,
All reviews by a user (reachable from user page): https://ifdb.org/allreviews?id=ug9r86p2jeyo8p21&ratings=yes
Link to specific review (under "More options → Direct link"): https://ifdb.org/viewgame?id=nw9abspvs8q233qu&review=75539

Can you be more specific about which page you're looking at, and not finding the direct link?

**Comment by russo2116** [comment]
I mean the latter - sorry if the original issue wasn’t clear, but “more options” doesn’t appear for one’s own reviews, as it’s replaced by a “revise your review” link.  Of course you can just log out to get it to reappear, but that can get pretty annoying (and might not occur to some users).  Sent from my iPhoneOn Oct 22, 2023, at 2:48 AM, Ori Avtalion ***@***.***> wrote:﻿
Do you mean a link to all of your reviews, or a single review? Both types are supported.
e.g.,
All reviews by a user (reachable from user page): https://ifdb.org/allreviews?id=ug9r86p2jeyo8p21&ratings=yes
Link to specific review (under "More options → Direct link"): https://ifdb.org/viewgame?id=nw9abspvs8q233qu&review=75539
Can you be more specific about which page you're looking at, and not finding the direct link?
