### ISSUE TITLE
Adding more than 1 suggested similar game fails

### ISSUE THREAD

**Issue by NilsFagerburg** [iftechfoundation/ifdb-suggestion-tracker#4]
Adding a suggested similar game (on the crossrec page, e.g. https://ifdb.tads.org/crossrec?game=v41tydzz51khw6ab&edit) to a game for which you've already added a suggested similar game fails with the following error message:

>  An error occurred deleting the suggestion from the database. You might try the operation again in a few minutes, or contact us if the problem persists.

**Comment by Durafen** [comment]
This happens because column "fromgame" in table "crossrecs" defined as primary key, so only one entry can be suggested for every game.
I tried  setting "created" as a primary key, and the suggestions function is back to work as intended.

**Comment by lkcampbell** [comment]
@Durafen, what about putting a new `id` column in the table as the primary key and remove `fromgame` as a primary key? `id` seems to be the default primary key column name.

**Comment by Durafen** [comment]
Both of this options will work.
Removing the index is the easier way (no need for coding, only table altering).

**Comment by Durafen** [comment]
It's better to have a unique key, so another simple option may be to set `created` as primary unique key.

```
MariaDB [ifdb]> DESCRIBE crossrecs;
+----------+-------------+------+-----+---------+-------+
| Field    | Type        | Null | Key | Default | Extra |
+----------+-------------+------+-----+---------+-------+
| fromgame | varchar(32) | NO   | PRI | NULL    |       |
| togame   | varchar(32) | NO   |     | NULL    |       |
| userid   | varchar(32) | NO   | MUL | NULL    |       |
| notes    | mediumtext  | YES  |     | NULL    |       |
| created  | datetime    | NO   |     | NULL    |       |
+----------+-------------+------+-----+---------+-------+
```
@dfabulich Opinion? Which way is going to be more suitable?
