### ISSUE TITLE
Prevent IFDB from recommending certain games/authors

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#41]
In cases where authors have violated our code of conduct, we _could_ delete the author's game listings, but instead of that, it would be better to restrict linking to their listings.

I'm imagining:

* Put a banner on the game saying that links to the game were restricted
* Never show these games on the home page (New on IFDB, IFDB Recommends…)
* Never show these games in "more like this" recommendations
* Hide these games in search results by default, but add a banner saying "some search results were removed, click here to see them all"
* Hide these games in IFDB Lists as well (including the IFDB Top 100), again including a banner "some entries were removed, click here to see them all"

**Comment by qdacsvx** [comment]
To ban (and delete) or not ban is simple. Why should there be a Twilight Zone where you can find a game in the database but it is somehow suppressed or excluded from popular pages?

Is a game guilty of the sins of the author? This suggestion seems wrong-headed. IFDB shouldn't be prejudiced against games that have not broken any rule. Perhaps the author's identity should be masked with a note that that user is banned.

**Comment by qdacsvx** [comment]
Regarding secretly hiding games. How effective will this be to influence people to comply with community norms? If I don't know why my game lost it's ratings and reviews how will I associate my past behaviour (i.e. wrongdoing if I'm guilty) with this surprise event? Third-parties who see nulled games might speculate that it's a bug or a hacking attack.

What if I ask an admin to delete my "hacked" game so I can make a new game page?

What if I just make a new game page anyways to replace the old "hacked" one without asking anybody?

**Comment by jpcompton** [comment]
Cragne Manor is an easy genuine "whatabout" here. It's not a hypothetical that at least one named tagged author has been/would be subject to some form of sanction, right?

**Comment by PatientRock** [comment]
I agree with the original list of actions to take when an author has violated the terms of conduct. For the sake of historical purposes the game is still within the database and still discoverable in a number of ways. The author and their work should not receive the benefits of promotion after violating the Code of Conduct.

"Is a game guilty of the sins of the author?" Yes it is. The Code of Conduct isn't frivolous nor does it ask much of our behavior. If an author cannot respect those basic tenets, they should not be able to reap the benefits of the platform.

There will always be edge cases like Cragne Manor. I'm one of the (many) authors of that particular game. Games such as Cragne Manor have enough of a place in Interactive Fiction's history that not overtly appearing in searches will not hurt it. Further, the game will still be linked to me in my author profile.

**Comment by jpcompton** [comment]
If only it [didn't overtly appear in almost every search](https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/168)!

It is my impression that IFTF puts a fairly low priority on _consistency_ in moderation (favoring what its leadership considers The Right Thing over strict repeatability) and so I find it fairly unlikely that hiding Cragne would be the outcome. I'd expect something more along the lines of "a Naughty Author's works done either solo, or with relatively Unimportant people, will be put in a bin. Those works hitched to the wagon of the Important will remain."

But time will tell.

**Comment by dfabulich** [comment]
We wound up implementing this, but we currently only plan it to use it on games where the author has instigated a brigade to upvote their game on IFDB.
