### ISSUE TITLE
Update README with instructions on how to run patch-schema.sql scripts

### ISSUE THREAD

**Issue by salty-horse** [iftechfoundation/ifdb-suggestion-tracker#435]
Some of the recent changes to the database aren't in the development environment's database dump, so they were added into patch-schema*.sql scripts.

Are those supposed to be applied automatically, or manually? It doesn't seem to happen automatically, unless I'm missing an obvious step.

**Comment by dfabulich** [comment]
You have to re-run `./prepare_dev_environment.sh`. But it should work at that point

**Comment by salty-horse** [comment]
That definitely doesn't work for me. When are the scripts in `initdb/` supposed to be executed?

**Comment by dfabulich** [comment]
To be clear, here's how I run it:

```
./prepare_dev_environment.sh && docker compose down && docker compose up --build
```

The scripts in `initdb` are meant to be run when you `docker compose up` after running `docker compose down`.

**Comment by salty-horse** [comment]
That worked for me, thanks.
