### ISSUE TITLE
No obvious way to add cross-recommendations to listings that don't already have them

### ISSUE THREAD

**Issue by alice-blue** [iftechfoundation/ifdb-suggestion-tracker#437]
_Lost Pig_, for example, has a cross-recommendation: _A Flustered Duck_, which has a "Suggest a game" link under it: [https://ifdb.org/viewgame?id=mohwfk47yjzii14w](https://ifdb.org/viewgame?id=mohwfk47yjzii14w)

But if you go to a listing that has no cross-recommendations, for example, [https://ifdb.org/viewgame?id=6l81m82xf294621g](https://ifdb.org/viewgame?id=6l81m82xf294621g),  I see no link to "Suggest a game."

**Comment by salty-horse** [comment]
Would it be ok to have an empty section like this?
``
If you enjoyed Game X...
  Related Games
     There are no related games.
     Suggest a game
``

Maybe the text can be more active like "No-one has a suggested a related game. `<link>`Add one`</link>`."

But I think the link should have the same text, so make it easier to find by name.

**Comment by alice-blue** [comment]
If you want the text to be similar to what's already there, maybe you could do something like this:


If you enjoyed _Lost Pig_...
Related Games
You can recommend a game for other people who liked _Lost Pig_:
`<link>`Suggest a game`</link>`

**Comment by dfabulich** [comment]
![image](https://github.com/iftechfoundation/ifdb-suggestion-tracker/assets/96150/13c623f1-5f8b-4e37-90e7-b424735f0921)

**Comment by dfabulich** [comment]
I think I want to close this? (But maybe it should be clearer anyway?)

**Comment by alice-blue** [comment]
Whatever you  think. Thanks for showing where the link is.
