### ISSUE TITLE
Implicit IFID search skips fulltext search

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#439]
Search for "Adventure."

Actual: The search redirects to https://ifdb.org/viewgame?id=879ockxnsj91xq8y which has an IFID `ADVENTURE`
Expected: That game should appear on the list, but other games should appear as well

**Comment by salty-horse** [comment]
Did you delete the `ADVENTURE` IFID from the database? I only see it in my local copy.

**Comment by alice-blue** [comment]
If you mean the live database, I believe some volunteers went through and deleted a lot of invalid IFIDs, probably including that one:
https://intfiction.org/t/ifdb-search-anomaly/66571/13
