### ISSUE TITLE
Deadflag

### ISSUE THREAD

**Issue by 6ru35l4y3r** [iftechfoundation/ifdb-suggestion-tracker#44]
It might be that the following is already being dealt with, or that things will be solved in a different way. That's fine, I may have missed the discussion. This tackles #22, #25 and #41.

I would suggest to add two "deadflag" variables to the database, connected to an author, that are 0 by default, and if set to 1 define that (flag 1) the reviews of the respective author are not to be displayed and counted and that (flag 2) the games of the author are not to be displayed and counted into lists and analysis. That's how I as a complete layman would make the database "fit" for when we've decided on how to deal with malicious reviews and/or authors. May be a stupid idea, in that case just delete this suggestion.

**Comment by curiousdannii** [comment]
We probably want the freedom to have more than just a binary option. Other statuses could be pending, deleted, draft, etc.

**Comment by dfabulich** [comment]
Currently IFDB has a "shadowban" feature that hides all reviews and comments from known trolls. I believe it doesn't do anything to game listings submitted by the troll, and especially doesn't do anything to games that the troll has authored (if the game listing was submitted by another user).

**Comment by dfabulich** [comment]
I think this is now covered by other related features.
