### ISSUE TITLE
IF Archive uploader doesn't include the TUID

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#449]
When you Edit a Game Listing and click the link to "Upload it to the IF Archive," we fill out a lot of information on the form, and, when you go to upload the file to the archive, we also include a freshly generated `ifdbid` parameter, which matches the pending link.

… but we don't include the TUID of the game listing anywhere! This seems like an oversight.

**Comment by erkyrath** [comment]
So: you pass `tuid` over to the upload form; the Archive side stores that field in the uploads table; displays it on all relevant upload data pages, and then passes it back in the notify call. Easy enough.
