### ISSUE TITLE
Display all tags in a list as well as the cloud

### ISSUE THREAD

**Issue by alyshkalia** [iftechfoundation/ifdb-suggestion-tracker#499]
It would be helpful if all tags applied to games could be viewed in a list along with a count of the number of times each has been used, rather than just having the tag cloud that indicates frequency by font size. This is partly an accessibility issue for screenreader users, as well as a general convenience issue.

**Comment by alice-blue** [comment]
Would it make sense to have a page with all of the tags in a table, similar to the table that appears on a game page? (Only it would include all tags on IFDB, so it would be a lot bigger?) That table has the frequency in parentheses next to each tag.
![tag table](https://github.com/user-attachments/assets/6ae86db6-361a-4e8c-8706-b054e397ee13)

**Comment by alyshkalia** [comment]
> Would it make sense to have a page with all of the tags in a table, similar to the table that appears on a game page? 

Yeah, that would be great! I didn't know about that existing list view, but it really isn't very useful in its current format...
