### ISSUE TITLE
Add "Inspired by" cross reference

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#501]
https://intfiction.org/t/new-type-of-cross-reference-for-ifdb/71433

> There is a “cross references” section on IFDB pages. Maybe it would be nice to add “inspired by” to the list of options there?

The current list of options is:

```
MariaDB [ifdb]> select * from gamexreftypes;
+---------+---------------------------+-----------------------------+---------------+
| reftype | fromname                  | toname                      | tonames       |
+---------+---------------------------+-----------------------------+---------------+
|       1 | adapted from              | adapted by                  | adaptations   |
|       2 | <language> translation of | translated to <language> in | translations  |
|       3 | spoof of                  | spoofed by                  | spoofs        |
|       4 | <system> port of          | ported to <system> in       | ports         |
|       5 | sequel to                 | followed by sequel          | sequels       |
|       6 | prequel to                | followed by prequel         | prequels      |
|       7 | remake of                 | remade as                   | remakes       |
|       8 | makes reference to        | referenced in               | referenced in |
+---------+---------------------------+-----------------------------+---------------+
```

**Comment by dfabulich** [comment]
I think fixing this would be a one-liner SQL statement.

What would we want the `toname` to be? e.g. if game X inspires Y, we'd say that Y is "inspired by" X, and that X "inspired" Y?

These cross references show up in the "Game Details" section, so, for example, on Counterfeit Monkey, it might say "Inspired by [Leather Goddesses of Phobos](https://ifdb.org/viewgame?id=3p9fdt4fxr2goctw)," and on LGoP it might just say "Inspired [Counterfeit Monkey](https://ifdb.org/viewgame?id=aearuuxv83plclpl)".

I wonder if "Inspired [Counterfeit Monkey](https://ifdb.org/viewgame?id=aearuuxv83plclpl)" is clear enough out of context, especially without any preposition.

Maybe:
* Drew inspiration from [Leather Goddesses of Phobos](https://ifdb.org/viewgame?id=3p9fdt4fxr2goctw)
* Gave inspiration to [Counterfeit Monkey](https://ifdb.org/viewgame?id=aearuuxv83plclpl)"

Or maybe instead of "inspired" we could say "influenced"? (But still, "Influenced [Counterfeit Monkey](https://ifdb.org/viewgame?id=aearuuxv83plclpl)" feels confusing out of context.)

**Comment by thexenographer** [comment]
I don't see a reason to say anything other than "Inspired by X" on Y's page; I think that wording is pretty clear. If "Inspired Y" seems too vague, I think "Gave inspiration to" is good; "Influenced" is, if anything, even vaguer.

**Comment by dfabulich** [comment]
So, like this?

* Inspired by [Leather Goddesses of Phobos](https://ifdb.org/viewgame?id=3p9fdt4fxr2goctw)
* Gave inspiration to [Counterfeit Monkey](https://ifdb.org/viewgame?id=aearuuxv83plclpl)

**Comment by thexenographer** [comment]
Yes - it's maybe a bit inelegant, but I think at least it's clear.

**Comment by dfabulich** [comment]
Done!
