### ISSUE TITLE
search/sort by submission date

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#61]
You can search/sort games by publication date, but not by submission date. For example, if an old game was newly added to IFDB yesterday, it doesn't appear in `published:2021-` searches.

**Comment by lkcampbell** [comment]
@dfabulich, to clarify, we are just looking at the creation date here. The last modified date would not be taken into consideration, correct?

**Comment by dfabulich** [comment]
That's what I was imagining, yes.

**Comment by alice-blue** [comment]
You could maybe consider "added" or "listed" as a search parameter.

**Comment by lkcampbell** [comment]
@alice-blue, sure, I can do that. I like "added" better. It's shorter and encompasses the idea of "created" and "submitted" in one word.

**Comment by lkcampbell** [comment]
@dfabulich please close this issue as fixed.
