### ISSUE TITLE
Non-square cover art should use transparent pixels to fill instead of white

### ISSUE THREAD

**Issue by brirush84** [iftechfoundation/ifdb-suggestion-tracker#67]
Looks bad in 'dark mode' style sheets

**Comment by brirush84** [comment]
Looks like this stackexchange question from 5 years ago might help:

https://stackoverflow.com/questions/30999323/how-to-insert-image-with-transparent-background-in-html

**Comment by dfabulich** [comment]
What's an example game with non-square cover art?

**Comment by brirush84** [comment]
Right, I was going to say search for choicescript games.
