### ISSUE TITLE
The allnew page has unicode issues

### ISSUE THREAD

**Issue by dougo** [iftechfoundation/ifdb-suggestion-tracker#7]
The "New on IFDB" page displays Unicode error symbols (question mark diamonds) instead of accented characters, smart quotes, etc:

https://ifdb.tads.org/allnew

**Comment by cibersheep** [comment]
Looks like the code for the page is broken: look at the first line of the html

```
<br><html>
<head>
[...]
   <title>New on IFDB</title>
   <link rel="stylesheet" href="/ifdb.css">      </head>
<body>
```

**Comment by Durafen** [comment]
There is a `echo` leftover from debugging  in `allnew` page.

 [PR: newitems - removing unnecessary br that affects allnew page](https://github.com/iftechfoundation/ifdb/pull/14) will fix it.

**Comment by dfabulich** [comment]
The `<br>` is real, but it's not the true cause of the problem. @Durafen's PR https://github.com/iftechfoundation/ifdb/pull/14 removes the stray `<br>`, but I don't reproduce the Unicode issues in the https://github.com/iftechfoundation/ifdb dev environment at all, with or without `<br>`.

For some reason, https://ifdb.tads.org/allnew declares itself to be UTF-8:

```
% curl -s --head https://ifdb.tads.org/allnew | grep -i Content-Type
content-type: text/html; charset=UTF-8
```

But that header is wrong; the page is really in charset=ISO-8859-1. The browser displays the Unicode unknown character symbols "�" when it encounters ISO-8859-1 which is invalid Unicode.

On my dev box, this doesn't repro:

```
% curl -s --head http://localhost:8080/allnew | grep -i Content-Type
Content-Type: text/html; charset=ISO-8859-1
```

I therefore feel optimistic that this is going to fix itself automagically when we deploy the site. 🤷

**Comment by dougo** [comment]
This looks fixed on the new site. Yay! Feel free to close this issue.
