### ISSUE TITLE
Moderators need a way to delete tags

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#71]
Apropos #6, if we don't allow just _anyone_ to delete tags, then there at least needs to be a way for moderators to delete tags.

Right now, the only workaround for this is to impersonate the user who added the tag, but there's no convenient way of even seeing which user added which tag. So you first have to query the DB for `SELECT * FROM gametags WHERE gameid='blah' and tag = 'blah'` to figure out which user added the tag, then impersonate _that_ user to remove the tag.

**Comment by qdacsvx** [comment]
I will support this if the implementation could be used by normal users but is only guarded by a privilege check? E.g. there could be a new button "remove tags" showing the tags menu, and you can tick any tags to remove them.

To implement tags being removed from the public list but not from the user's private list there could be a new column in tags recording the type of event add/remove and removals could be recorded. Side effect: there is a complete log of removals. The list of removals will be a filter list (sorted by date) when computing the public tags. (This will require JavaScript changes.) Younger add/removal events override older.

**Comment by dfabulich** [comment]
This was done in https://github.com/iftechfoundation/ifdb/pull/28
