### ISSUE TITLE
"You previously voted Yes" immediately after voting

### ISSUE THREAD

**Issue by fos1** [iftechfoundation/ifdb-suggestion-tracker#75]
When selecting "yes" to the Was This Review Helpful option at the bottom of a review, it seems to accept the "yes" but then generates an error saying that you have already voted yes.

**Comment by dfabulich** [comment]
![image](https://user-images.githubusercontent.com/96150/108125008-b3285880-705c-11eb-8d4a-94ed24f92734.png)

It's not an "error" message but I'd say it is confusing to say "You previously voted Yes" _immediately_ after voting.

**Comment by Durafen** [comment]
In the [code](https://github.com/iftechfoundation/ifdb/blob/1c211b9462342e7c9c26b5683a4256405176f779/www/reviews.php#L138-L153) its always show the last vote (no matter what voted beforehand).
