### ISSUE TITLE
Allow users to remove their own review votes

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb-suggestion-tracker#76]
Currently a normal user may only change their review vote, they may not remove it. But what if I voted by mistake?

**Comment by Durafen** [comment]
Duplication of [No way to remove a review vote #195](https://github.com/iftechfoundation/ifdb-suggestion-tracker/issues/195) and should be closed in [Reset review vote option #66](https://github.com/iftechfoundation/ifdb/pull/66).
