### ISSUE TITLE
IFDB should link to the suggestion box

### ISSUE THREAD

**Issue by qdacsvx** [iftechfoundation/ifdb-suggestion-tracker#88]
There should be a suggestion box on IFDB.

Should it be open to the public (no login needed)? There could be a field to disclose your email.

After a chance for moderators to glance at incoming messages they could be posted on a suggestions page where users could vote / flag / comment.

**Comment by dfabulich** [comment]
IMO, this is two issues:

1. We should have a better suggestion tracker. I've filed this as #100 
2. Whatever suggestion tracker we're currently using, we should link to it from IFDB. I'm going to update this issue to just be about that.

**Comment by qdacsvx** [comment]
I don't know how much take up there will be for a link on live [IFDB](https://ifdb.tads.org/). Many people come to IFDB for entertainment or just to read reviews. Someone in a groove won't necessarily notice a new link for suggestions on IFDB.

**Comment by qdacsvx** [comment]
Announcing on the front page news should be fairly effective. People on IFDB will share the news spreading it.
