### ISSUE TITLE
Add a really strict Content-Security-Policy

### ISSUE THREAD

**Issue by dfabulich** [iftechfoundation/ifdb-suggestion-tracker#99]
IFDB is mostly a server-side app, so a very strict Content-Security-Policy will broadly protect us from XSS attacks.

**Comment by salty-horse** [comment]
There are CSP errors on pages that include captcha.php which has `<script src='https://www.google.com/recaptcha/api.js'></script>`
```
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
```
And these as well:
```
Partitioned cookie or storage access was provided to “https://www.google.com/recaptcha/...” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Request to access cookie or storage on “https://www.google.com/js/...” was blocked because it came from a tracker and content blocking is enabled.

**Comment by dfabulich** [comment]
https://developers.google.com/recaptcha/docs/faq documents how to get recaptcha to work.

I think we'd make aggressive use of nonces to handle the various inline scripts available on the page.

**Comment by dfabulich** [comment]
https://github.com/iftechfoundation/ifdb/pull/242 did a lot of this, but I still need to remove `style-src 'unsafe-inline'`.
